### ISSUE TITLE
matches comparer not supported

### ISSUE THREAD

**Issue by steffenschebesta** [jtwig/jtwig#259]
[The `matches` comparer](http://twig.sensiolabs.org/doc/templates.html#comparisons) is never mentioned anywhere [[1](http://jtwig.org/jtwig-compatibility-matrix/), [2](http://jtwig.org/docs/jtwig-functions/string-functions/)] nor does it seem to be supported.

    {% if string matches '/^\S+@\S+\.\S+$/' %}

throws `org.jtwig.exception.ParseException: Wrong binary operation syntax`

**Comment by thomas-p-wilson** [comment]
I think this issue speaks to the need to implement extensible tests, ala http://twig.sensiolabs.org/doc/advanced.html#tests. I'm looking into the matter now. Will have more on it tomorrow.

**Comment by thomas-p-wilson** [comment]
While working on an extension API, I came across the matches operator. It does exist, at least in code. I'll check out why it isn't working. Also, what version of Jtwig are you using?

**Comment by thomas-p-wilson** [comment]
Alright, so that error you're receiving isn't exactly helpful, but doesn't actually indicate that it doesn't exist. In fact, the matches operator is working, but right now it accepts Java-style String.matches() expressions, which by default match the entire string and do not contain the start and end delimiters or the start and end anchors. I will look into fixing this so that it works as it does with Twig

**Comment by thomas-p-wilson** [comment]
For reference, this should be resolved in PR #289.

**Comment by lyncodev** [comment]
Implemented in jtwig-core v5.60
