### ISSUE TITLE
ValuesResolver

### ISSUE THREAD

**Issue by monvillalon** [jtwig/jtwig#303]
I was wondering if something akin to ValueResolver 
( https://github.com/jknack/handlebars.java#user-content-using-the-valueresolver ) in jknack/handlerbars
was available in Jtwig

For example if I create a JtwigModelMap like this:

        JsonNode node               = (new ObjectMapper()).readTree("{ \"a\": {\"b\": \"c\" }}");
        JtwigModelMap context   = new JtwigModelMap();
        context.add("json" , node );

Right now in my twig file I have to use as this:

        {{  json.get("a").get("b").asText() }}

But in my opinion the more natural approach would be to use it as this:

        {{ json.a.b }}

Thanks.

**Comment by thomas-p-wilson** [comment]
Hi @monvillalon! Thanks for your inquiry. Ideally, the more natural approach you suggest is how it should work. I will investigate the matter, and look into the implementation of ValueResolvers or something similar. Thanks for your feedback!

**Comment by lyncodev** [comment]
At the moment there is no native way of achieving this. A custom property resolver (http://jtwig.org/documentation/reference/core/environment#propertyResolvers) must be added in order to do this. You can check the test added to confirm such approach works (https://github.com/jtwig/jtwig-core/blob/master/src/test/java/org/jtwig/integration/issues/Issue303Test.java). 

The implementation provided is not optimal. Maybe an extension can be written to easily include such functionality onto Jtwig.
